name: Global Proxy Factory
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Python & Go
        uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - uses: actions/setup-go@v4
        with: { go-version: '1.21' }

      - name: Install Dependencies
        run: pip install aiohttp tqdm requests colorama rich psutil pysocks

      - name: Step 1 - Search Engine
        run: python engine.py

      - name: Step 2 - TCP Checker
        run: |
          cp raw_configs.txt tcp_checker/raw_configs.txt
          cd tcp_checker
          go build -o tcp_checker_bin tcp_checker.go
          ./tcp_checker_bin
          cd ..

      - name: Step 3 - Xray Hybrid Check (Private Stealth Mode)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # 1. Извлекаем наши модули из бункера
          git clone https://$GH_TOKEN@github.com/stella-packet-loss/stella-core-modules.git modules_backup
          cp -r modules_backup/modules/XrayChecker ./XrayChecker
          
          # 2. Магия инициализации для Python
          touch XrayChecker/__init__.py
          touch XrayChecker/data/__init__.py
          
          # 3. Подготовка бинарника Xray
          mkdir -p XrayChecker/bin
          curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o xray.zip xray -d XrayChecker/bin/
          chmod +x XrayChecker/bin/xray
          rm xray.zip
          
          # 4. Настройка путей и запуск
          export PYTHONPATH=$PYTHONPATH:$(pwd)/XrayChecker
          
          python proxy_manager.py
          
          if [ -f raw_udp.txt ]; then
            echo "🛡 Запуск Stella UDP Pro..."
            python stella_udp_pro.py -i raw_udp.txt -o distributor.txt -x ./XrayChecker/bin/xray
          fi

      - name: Step 4 - Push Results
        run: |
          echo "--- ИТОГОВАЯ СТАТИСТИКА ---"
          git config --local user.email "action@github.com"
          git config --local user.name "Stella-Global-Bot"
          git add .
          git commit -m "🚀 Hybrid Factory Sync | Stealth Mode | $(date)" || exit 0
          git push
