name: Stella-Sync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHECK_TIMEOUT: 10
      CHECK_THREADS: 100
      CHECK_URL: "http://cp.cloudflare.com/generate_204"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python engine.py
      - run: |
          chmod +x sing-box
          python checker.py
      - run: |
          git config --global user.name "Catsss3-Bot"
          git config --global user.email "vehesslav@gmail.com"
          git add distributor.txt
          git commit -m "🚀 Stella-Update: switched to Cloudflare check via Colab" || exit 0
          git push origin main
      - run: |
          curl -T distributor.txt --user "${{ secrets.MAIL_RU_LOGIN }}:${{ secrets.MAIL_RU_PASS }}" "https://webdav.cloud.mail.ru/distributor.txt"