name: Global Proxy Factory
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Python & Go
        uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - uses: actions/setup-go@v4
        with: { go-version: '1.21' }

      - name: Install Dependencies
        run: pip install aiohttp tqdm requests colorama rich psutil pysocks

      - name: Step 1 - Search Engine
        run: python engine.py

      - name: Step 2 - TCP Checker
        run: |
          cd tcp_checker
          go build -o tcp_checker_bin tcp_checker.go
          ./tcp_checker_bin
          cd ..

      - name: Step 3 - Xray Reality Check
        run: |
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o Xray-linux-64.zip xray && chmod +x xray
          git clone https://github.com/limingda1212/XrayChecker.git
          # ВОТ ТУТ КЛАДЕМ ВНУТРЬ И ДАЕМ ПРАВА
          cp xray XrayChecker/xray
          chmod +x XrayChecker/xray
          python proxy_manager.py

      - name: Step 4 - Push Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Stella-Global-Bot"
          git add raw_configs.txt tcp_checker/alive_tcp_full.txt distributor.txt
          git commit -m "Full Sync: Search -> TCP -> Xray | $(date)" || exit 0
          git push