name: 🚀 Auto-Update Sing-Box Distributor

on:
  schedule:
    - cron: '0 2 * * *' # Скрипт запускается строго один раз в сутки в 02:00 UTC
  workflow_dispatch: # Позволяет пинать скрипт кнопкой из панели GitHub Actions

permissions:
  contents: write

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ⚡ Run Sing-Box Check Engine
        run: python engine.py

      - name: 🚀 Commit and Push Clean Results
        run: |
          git config --global user.name "Catsss3"
          git config --global user.email "catsss@codeberg.org"
          
          git add distributor.txt subscribe.txt sources/* || true
          
          if git diff --staged --quiet; then
            echo "Изменений нет. Пропускаем пуш."
          else
            git commit -m "💥 Суточная фильтрация базы прокси"
            git push origin main
          fi
